SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
USE AP;

SELECT
	MIN(VendorName) AS FirstVendor,
	MAX(VendorName) AS LastVendor,
	COUNT(VendorName) AS NumberOfVendors
FROM
	AP..Vendors;
