SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
USE AP;

SELECT
	COUNT(DISTINCT VendorID) AS NumberOfVendors,
	COUNT(VendorID) AS NumberOfInvoices,
	AVG(InvoiceTotal) AS AverageInvoiceAmount,
	SUM(InvoiceTotal) AS TotalInvoiceAmount
FROM
	AP..Invoices
WHERE InvoiceDate > '2015-09-01';
