SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
USE AP;

SELECT
	InvoiceNumber,
	VendorName
FROM
	Vendors
	JOIN Invoices ON Vendors.VendorID = Invoices.VendorID;
