SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
USE AP;

SELECT
	InvoiceDate,
	InvoiceTotal,
	CAST(InvoiceDate AS VARCHAR) AS varcharDate,
	CAST(InvoiceTotal AS INT) AS integerTotal,
	CAST(InvoiceTotal AS VARCHAR) AS varcharTotal
FROM
	AP..Invoices;
