SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
USE AP;

SELECT
	VendorName + CHAR(13) + CHAR(10) + VendorAddress1 + CHAR(13)+CHAR(10)+VendorCity+', '+VendorState+' '+ VendorZipCode
FROM
	AP..Vendors
WHERE VendorID = 1;
