SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
USE AP;

SELECT
	VendorCity
FROM
	Vendors
WHERE VendorCity LIKE 'SAN%';

SELECT
	VendorName
FROM
	Vendors
WHERE VendorName LIKE 'COMPU_ER%';

SELECT
	VendorContactLName
FROM
	Vendors
WHERE VendorContactLName LIKE 'DAMI[EO]N%';
