SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
USE AP;

SELECT
	PaymentDate,
	COALESCE(PaymentDate, '1900-01-01') AS NewDate
FROM
	AP..Invoices;

SELECT
	PaymentDate,
	ISNULL(PaymentDate, '1900-01-01') AS NewDate
FROM
	AP..Invoices;
