SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
USE AP;

SELECT
	InvoiceDate,
	COUNT(*) AS InvoiceQty,
	SUM(InvoiceTotal) AS InvoiceSum
FROM
	AP..Invoices
GROUP BY InvoiceDate
HAVING InvoiceDate BETWEEN '2016-01-01' AND '2016-01-31'
	AND COUNT(*) > 1
	AND SUM(InvoiceTotal) > 100
ORDER BY InvoiceDate DESC;

SELECT
	InvoiceDate,
	COUNT(*) AS InvoiceQty,
	SUM(InvoiceTotal) AS InvoiceSum
FROM
	AP..Invoices
WHERE InvoiceDate BETWEEN '2016-01-01' AND '2016-01-31'
GROUP BY InvoiceDate
HAVING COUNT(*) > 1
	AND SUM(InvoiceTotal) > 100
ORDER BY InvoiceDate DESC;
